language: generic
sudo: required
services:
    - docker


before_install:
  - docker build -t jamesbrunke/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jamesbrunke/react npm run test
